### ISSUE TITLE
Field Mappings Incorrect

### ISSUE THREAD

**Issue by cancan101** [jdebetaz/node-icloud-private-relay#2]
The field are not quite right here:
https://github.com/jdebetaz/node-icloud-private-relay/blob/ce62b87ed65a835261294941c4e8ca0e75a242f4/src/index.js#L10

Rather I think it should be:
```
countryCode: l[1], regionCode: l[2], cityName: l[3]
```

where regionCode is a subdivision according to ISO 3166: https://en.wikipedia.org/wiki/ISO_3166-2

**Comment by jdebetaz** [comment]
Hello,

The issue has just been corrected in the new version ([v1.2.1](https://github.com/jdebetaz/node-icloud-private-relay/releases/tag/v1.2.1))

Kind reagards,
Jonathan
